package com.kdu.bookingengine.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "travellerInfo")
public class TravellerInfo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String travellerInfoId;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    public TravellerInfo(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    //    @DynamoDBAttribute
//    private String phone;
//
//    @DynamoDBAttribute
//    private String email;
//
//    @DynamoDBAttribute
//    private PaymentInfo paymentInfo;
//
//    @DynamoDBAttribute
//    private BillingInfo billingInfo;
//
//    @DynamoDBAttribute
//    private boolean optMailingList;
//
//    @DynamoDBAttribute
//    private boolean agreement;

}